"""Add mixing_purpose columns to Ingredient model

Revision ID: 621e16623193
Revises: 79159b6bd34a
Create Date: 2024-08-24 21:46:31.224904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621e16623193'
down_revision = '79159b6bd34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mixing_purpose_korean', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mixing_purpose_english', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('mixing_purpose_english')
        batch_op.drop_column('mixing_purpose_korean')

    # ### end Alembic commands ###
