"""Initial migration with simplified columns

Revision ID: 79159b6bd34a
Revises: 54244d75eda2
Create Date: 2024-08-24 21:43:53.655004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79159b6bd34a'
down_revision = '54244d75eda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_korean', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('name_english', sa.String(length=100), nullable=True))
        batch_op.drop_column('use_case')
        batch_op.drop_column('mixing_purpose_english')
        batch_op.drop_column('description')
        batch_op.drop_column('environmental_impact')
        batch_op.drop_column('name')
        batch_op.drop_column('mixing_purpose_korean')
        batch_op.drop_column('safety_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safety_rating', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mixing_purpose_korean', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('environmental_impact', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('mixing_purpose_english', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('use_case', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('name_english')
        batch_op.drop_column('name_korean')

    # ### end Alembic commands ###
